# Generated by Django 4.2.18 on 2025-01-25 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_managment', '0003_alter_dish_cooks_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(blank=True, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
